config/routes.rb
Rails.application.routes.draw do
  resources :subject_has_classifications
  resources :subject_heading_types do
    resources :subjects
  end
  resources :subject_heading_type_has_subjects
  resources :classifications do
    resources :subject_has_classifications
  end
  resources :classification_types do
    resources :classifications
  end
  resources :subject_types

  resources :work_has_subjects

  resources :subjects do
    resources :works, :controller => 'manifestations'
    resources :subject_heading_types
    resources :subject_has_classifications
    resources :work_has_subjects
    resources :classifications
  end

  resources :works, :controller => 'manifestations', :except => [:index, :new, :create] do
    resources :subjects
    resources :work_has_subjects
  end

  resources :manifestations do
    resources :work_has_subjects
    resources :subjects
  end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :parent_id, :use_term_id, :term, :term_transcription,
    :subject_type_id, :note, :required_role_id

  has_many :work_has_subjects, :dependent => :destroy
  has_many :works, :through => :work_has_subjects, :class_name => 'Manifestation'
  belongs_to :subject_type
  has_many :subject_has_classifications, :dependent => :destroy
  has_many :classifications, :through => :subject_has_classifications
  belongs_to :subject_type, :validate => true
  has_many :subject_heading_type_has_subjects
  has_many :subject_heading_types, :through => :subject_heading_type_has_subjects
  belongs_to :required_role, :class_name => 'Role', :foreign_key => 'required_role_id'

  validates_associated :subject_type
  validates_presence_of :term, :subject_type

  attr_accessor :classification_id, :subject_heading_type_id

  searchable do
    text :term
    time :created_at
    integer :required_role_id
    integer :work_ids, :multiple => true
  end

  normalize_attributes :term

  paginates_per 10
end

# == Schema Information
#
# Table name: subjects
#
#  id                 :integer          not null, primary key
#  parent_id          :integer
#  use_term_id        :integer
#  term               :string(255)
#  term_transcription :text
#  subject_type_id    :integer          not null
#  scope_note         :text
#  note               :text
#  required_role_id   :integer          default(1), not null
#  lock_version       :integer          default(0), not null
#  created_at         :datetime
#  updated_at         :datetime
#  deleted_at         :datetime
#

app/models/subject_type.rb
class SubjectType < ActiveRecord::Base
  attr_accessible :name, :display_name, :note
  include MasterModel
  default_scope :order => "position"
  has_many :subjects
end

# == Schema Information
#
# Table name: subject_types
#
#  id           :integer          not null, primary key
#  name         :string(255)      not null
#  display_name :text
#  note         :text
#  position     :integer
#  created_at   :datetime
#  updated_at   :datetime
#

app/controllers/subjects_controller.rb
# -*- encoding: utf-8 -*-
class SubjectsController < ApplicationController
  load_and_authorize_resource :except => :index
  authorize_resource :only => :index
  before_filter :get_work, :get_subject_heading_type, :get_classification
  before_filter :prepare_options, :only => :new
  after_filter :solr_commit, :only => [:create, :update, :destroy]
  #cache_sweeper :subject_sweeper, :only => [:create, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    sort = {:sort_by => 'created_at', :order => 'desc'}
    case params[:sort_by]
    when 'name'
      sort[:sort_by] = 'term'
    end
    sort[:order] = 'asc' if params[:order] == 'asc'

    search = Subject.search(:include => [:works])
    query = params[:query].to_s.strip
    unless query.blank?
      @query = query.dup
      query = query.gsub('　', ' ')
      search.build do
        fulltext query
      end
    end

    search.build do
      order_by sort[:sort_by], sort[:order]
    end

    unless params[:mode] == 'add'
      work = @work
      classification = @classification
      subject_heading_type = @subject_heading_type
      search.build do
        with(:work_ids).equal_to work.id if work
        with(:classification_ids).equal_to classification.id if classification
        with(:subject_heading_type_ids).equal_to subject_heading_type.id if subject_heading_type
      end
    end

    role = current_user.try(:role) || Role.default_role
    search.build do
      with(:required_role_id).less_than_or_equal_to role.id
    end

    page = params[:page] || 1
    search.query.paginate(page.to_i, Subject.default_per_page)
    @subjects = search.execute!.results
    session[:params] = {} unless session[:params]
    session[:params][:subject] = params

    flash[:page_info] = {:page => page, :query => query}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @subjects }
      format.rss
      format.atom
    end
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    if params[:term]
      subject = Subject.where(:term => params[:term]).first
      redirected_to subject
      return
    end

    if @work
      @subject = @work.subjects.find(params[:id])
    #else
    #  @subject = Subject.find(params[:id])
    end
    search = Sunspot.new_search(Manifestation)
    subject = @subject
    search.build do
      with(:subject_ids).equal_to subject.id if subject
    end
    page = params[:work_page] || 1
    search.query.paginate(page.to_i, Manifestation.default_per_page)
    @works = search.execute!.results

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @subject }
      format.js
    end
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
    @subject.classification_id = @classification.id if @classification
    @subject.subject_heading_type_id = @subject_heading_type.id if @subject_heading_type

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @subject }
    end
  end

  # GET /subjects/1/edit
  def edit
    if @work
      @subject = @work.subjects.find(params[:id])
    #else
    #  @subject = Subject.find(params[:id])
    end
    @subject_types = SubjectType.all
  end

  # POST /subjects
  # POST /subjects.json
  def create
    if @work
      @subject = @work.subjects.new(params[:subject])
    else
      @subject = Subject.new(params[:subject])
    end
    classification = Classification.find(@subject.classification_id) if @subject.classification_id.present?
    subject_heading_type = SubjectHeadingType.find(@subject.subject_heading_type_id) if @subject.subject_heading_type_id.present?

    respond_to do |format|
      if @subject.save
        @subject.classifications << classification if classification
        @subject.subject_heading_types << subject_heading_type if subject_heading_type
        format.html { redirect_to @subject, :notice => t('controller.successfully_created', :model => t('activerecord.models.subject')) }
        format.json { render :json => @subject, :status => :created, :location => @subject }
      else
        @classification = classification
        @subject_heading_type = subject_heading_type
        prepare_options
        format.html { render :action => "new" }
        format.json { render :json => @subject.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /subjects/1
  # PUT /subjects/1.json
  def update
    if @work
      @subject = @work.subjects.find(params[:id])
    #else
    #  @subject = Subject.find(params[:id])
    end

    respond_to do |format|
      if @subject.update_attributes(params[:subject])
        format.html { redirect_to @subject, :notice => t('controller.successfully_updated', :model => t('activerecord.models.subject')) }
        format.json { head :no_content }
      else
        prepare_options
        format.html { render :action => "edit" }
        format.json { render :json => @subject.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    if @work
      @subject = @work.subjects.find(params[:id])
    #else
    #  @subject = Subject.find(params[:id])
    end
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url }
      format.json { head :no_content }
    end
  end

  private
  def prepare_options
    @subject_types = SubjectType.all
  end
end

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| -%>
  <%= f.error_messages -%>
  <div class="field">
    <%= f.label t('activerecord.models.subject_type') -%>
    <%= f.select(:subject_type_id, @subject_types.collect{|s| [s.display_name.localize, s.id]}) -%>
  </div>

  <div class="field">
    <%= f.label :term -%><br />
    <%= f.text_field :term -%>
  </div>
  <div class="field">
    <%= f.label :term_transcription -%><br />
    <%= f.text_field :term_transcription -%>
  </div>
  <div class="field">
    <%= f.label :note -%><br />
    <%= f.text_area :note -%>
  </div>
  <%- if @classification -%>
    <div class="field">
      <%= f.label t('activerecord.models.classification') -%>
      <%= link_to @classification.category, @classification -%>
      <%= f.hidden_field :classification_id -%>
    </div>
  <%- end -%>
  <%- if @subject_heading_type -%>
    <div class="field">
      <%= f.label t('activerecord.models.subject_heading_type') -%>
      <%= link_to @subject_heading_type.display_name.localize, @subject_heading_type -%>
      <%= f.hidden_field :subject_heading_type_id -%>
    </div>
  <%- end -%>
  <div class="actions">
    <%= f.submit %>
  </div>
<%- end -%>

app/views/subjects/_index.html.erb
<div id="content_detail" class="ui-corner-all">
<h1 class="title"><%= t('page.listing', :model => t('activerecord.models.subject')) -%></h1>
<div id="content_list">
  
<div class="search_form">
  <%= form_for :subjects, :url => subjects_path, :html => {:method => 'get'} do -%>
    <p>
      <%= t('page.search_term') -%>: <%= search_field_tag 'query', h(@query), {:id => 'search_form_top', :class => 'search_form', :placeholder => t('page.search_term')} -%>
      <%= submit_tag t('page.search') -%>
    </p>
  <%- end -%>
</div>

<table class="table table-striped index">
  <tr>
    <th><%= t('activerecord.attributes.subject.term') -%></th>
    <th></th>
  </tr>
  <%- subjects.each do |subject| -%>
    <tr class="line<%= cycle("0", "1") -%>">
      <td><%= link_to subject.term, subject -%></td>
      <td>
        <%- if can? :update, subject -%>
          <%= link_to t('page.edit'), edit_subject_path(subject) -%>
        <%- end -%>
        <%- if can? :destroy, subject -%>
          <%= link_to t('page.destroy'), subject, :data => {:confirm => t('page.are_you_sure')}, :method => :delete -%>
        <%- end -%>
      </td>
    </tr>
  <%- end -%>
</table>

<%= paginate(subjects) -%>
</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <%- if can? :create, Subject -%>
      <%- if @subject_heading_type -%>
        <li><%= link_to t('page.new', :model => t('activerecord.models.subject')), new_subject_heading_type_subject_path(@subject_heading_type) -%></li>
      <%- else -%>
        <li><%= link_to t('page.new', :model => t('activerecord.models.subject')), new_subject_path -%></li>
      <%- end -%>
    <%- end -%>
  </ul>
</div>

app/views/subjects/_index_classification.html.erb
<div id="content_detail" class="ui-corner-all">
<h1 class="title"><%= t('page.listing', :model => t('activerecord.models.subject')) -%></h1>
<div id="content_list">

<h2 class="resource_title"><%= link_to @classification.category, @classification -%></h2>
<div class="search_form">
  <%= form_for :subjects, :url => classification_subjects_path(@classification), :html => {:method => 'get'} do -%>
    <p>
      <%= t('page.search_term') -%>: <%= search_field_tag 'query', h(@query), {:id => 'search_form_top', :class => 'search_form', :placeholder => t('page.search_term')} -%>
      <%= submit_tag t('page.search') -%>
      <%- if can? :create, WorkHasSubject -%>
        <%= render 'page/add' %>
      <%- end -%>
    </p>
  <%- end -%>
</div>

<table class="table table-striped index">
  <tr>
    <th><%= t('activerecord.attributes.subject.term') -%></th>
    <th></th>
  </tr>
  <%- subjects.each do |subject| -%>
    <tr class="line<%= cycle("0", "1") -%>">
      <td><%= link_to subject.term, subject -%></td>
      <td>
        <%- if can? :update, subject -%>
          <%= link_to t('page.edit'), edit_subject_path(subject) -%>
        <% end %>
      </td>
      <td>
        <%- if params[:mode] == 'add' -%>
          <%- if can? :update, subject -%>
            <%= link_to t('page.add'), new_classification_subject_has_classification_path(@classification, :subject_id => subject.id) unless @classification.subjects.include?(subject) -%>
          <% end %>
        <%- else -%>
          <%- has_classification = @classification.subject_has_classifications.find_by_subject_id(subject) -%>
          <% if can? :delete, has_classification %>
            <%= link_to t('page.destroy'), classification_subject_has_classification_path(@classification, has_classification), :data => {:confirm => t('page.are_you_sure')}, :method => :delete if has_classification -%>
          <% end %>
        <%- end -%>
      </td>
    </tr>
  <%- end -%>
</table>

<%= paginate(subjects) -%>
</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <%- if can? :create, Subject -%>
      <li><%= link_to t('page.new', :model => t('activerecord.models.subject')), new_classification_subject_path(@classification) -%></li>
    <%- end -%>
  </ul>
</div>

app/views/subjects/_index_work.html.erb
<div id="content_detail" class="ui-corner-all">
  <h1 class="title"><%= t('page.listing', :model => t('activerecord.models.subject')) -%></h1>
<div id="content_list">
  <h2 class="resource_title">
    [W]
    <%= link_to @work.original_title, @work -%>
  </h2>

<%= form_for :subjects, :url => work_subjects_path(@work), :html => {:method => 'get'} do -%>
  <p>
    <%= t('page.search_term') -%>: <%= search_field_tag 'query', h(@query), {:id => 'search_form_top', :class => 'search_form', :placeholder => t('page.search_term')} -%>
    <%= submit_tag t('page.search') -%>
    <%- if can? :create, WorkHasSubject -%>
      <%= render 'page/add' %>
    <%- end -%>
  </p>
<%- end -%>

<table class="table table-striped index">
  <tr>
    <th><%= t('activerecord.attributes.subject.term') -%></th>
    <th></th>
    <th></th>
  </tr>
  <%- subjects.each do |subject| -%>
    <tr class="line<%= cycle("0", "1") -%>">
      <td><%= link_to subject.term, subject -%></td>
      <td>
        <%- if can? :update, subject -%>
          <%= link_to t('page.edit'), edit_subject_path(subject) -%>
        <% end %>
      </td>
      <td>
        <%- if params[:mode] == 'add' -%>
          <%- if can? :update, subject -%>
            <%= link_to t('page.edit'), edit_subject_path(subject) -%>
            <%= link_to t('page.add'), new_work_work_has_subject_path(@work, :subject_id => subject.id) unless @work.subjects.include?(subject) -%>
          <% end %>
        <%- else -%>
          <%- has_subject = @work.work_has_subjects.find_by_subject_id(subject) -%>
          <%- if can? :delete, has_subject -%>
            <%= link_to t('page.destroy'), work_work_has_subject_path(@work, has_subject), :data => {:confirm => t('page.are_you_sure')}, :method => :delete -%>
          <% end %>
        <%- end -%>
      </td>
    </tr>
  <%- end -%>
</table>

<%= paginate(subjects) -%>
</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <%- if can? :create, Subject -%>
      <li><%= link_to t('page.new', :model => t('activerecord.models.subject')), new_work_subject_path(@work) -%></li>
    <%- end -%>
  </ul>
</div>

app/views/subjects/_show_work_list.html.erb
<div id="work">
<h2 class="resource_title"><%= t('page.listing', :model => t('activerecord.models.work')) -%></h2>
<table class="index">
<%- @works.each do |work| -%>
  <tr class="line<%= cycle("0", "1") -%>">
    <td>
      [W]
      <%= render 'manifestations/show_index', :manifestation => work -%>
    </td>
  </tr>
<%- end -%>
</table>

<%= paginate(@works, :param_name => :work_page, :remote => true) -%>
</div>

app/views/subjects/edit.html.erb
<div id="content_detail" class="ui-corner-all">
<h1 class="title"><%= t('page.editing', :model => t('activerecord.models.subject')) -%></h1>
<div id="content_list">
  <%= render 'form' %>
</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <li><%= link_to t('page.show'), @subject -%></li>
    <li><%= link_to t('page.back'), subjects_path -%></li>
  </ul>
</div>

app/views/subjects/index.html.erb
<%- case when @work -%>
  <%= render 'subjects/index_work', :subjects => @subjects -%>
<%- when @classification -%>
  <%= render 'subjects/index_classification', :subjects => @subjects -%>
<%- else -%>
  <%= render 'subjects/index', :subjects => @subjects -%>
<%- end -%>

app/views/subjects/new.html.erb
<div id="content_detail" class="ui-corner-all">
<h1 class="title"><%= t('page.new', :model => t('activerecord.models.subject')) -%></h1>
<div id="content_list">
  <%= render 'form' %>
</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <li><%= link_to t('page.back'), subjects_path -%></li>
  </ul>
</div>

app/views/subjects/show.html.erb
<div id="content_detail" class="ui-corner-all">
<h1 class="title"><%= t('page.showing', :model => t('activerecord.models.subject')) -%></h1>
<div id="content_list">
<p id="notice"><%= notice %></p>

<h2 class="resource_title">
  [S]
  <%= @subject.term -%>
</h2>
  <p>
    (<%= link_to_wikipedia(@subject.term) -%>)
  </p>

  <p>
    <%- @subject.subject_heading_types.uniq.each do |subject_heading_type| -%>
      <%= link_to subject_heading_type.display_name.localize, subject_heading_type -%>
    <%- end -%>
  </p>

  <p>
    <strong><%= t('activerecord.attributes.subject.term_transcription') -%>:</strong>
    <%= @subject.term_transcription -%>
  </p>

  <div id="tabs">
    <ul>
      <li title="active" class="selected"><a href="#work"><em><%= t('activerecord.models.work') -%></em></a></li>
      <li><a href="#classification"><em><%= t('activerecord.models.classification') -%></em></a></li>
    </ul>
    <%= render 'subjects/show_work_list' -%>
    <div id="classification">
      <table class="table table-striped index">
        <tr>
          <th><%= t('activerecord.attributes.classification.category') -%></th>
          <th><%= t('activerecord.models.classification_type') -%></th>
        </tr>
        <%- @subject.classifications.each do |classification| -%>
          <tr class="line<%= cycle("0", "1") -%>">
            <td><%= link_to classification.category, classification -%></td>
            <td><%= link_to classification.classification_type.name, classification.classification_type -%></td>
          </tr>
        <%- end -%>
      </table>

      <p>
        <strong><%= t('activerecord.attributes.subject.note') -%>:</strong>
        <%= @subject.note -%>
      </p>
    </div>
    </div>
  </div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <li><%= back_to_index(flash[:page_info]) -%></li>
    <%- if can? :create, SubjectHasClassification -%>
      <li><%= link_to t('page.edit'), edit_subject_path(@subject) -%></li>
      <li><%= link_to t('page.destroy'), subject_path(@subject), :data => {:confirm => t('page.are_you_sure')}, :method => :delete -%></li>
    <%- end -%>
    <li><%= link_to t('page.listing', :model => t('activerecord.models.classification')), subject_classifications_path(@subject) -%></li>
    <li><%= link_to t('page.listing', :model => t('activerecord.models.work')), subject_works_path(@subject) -%></li>
    <li><%= link_to t('page.listing', :model => t('activerecord.models.subject_heading_type')), subject_subject_heading_types_path(@subject) -%></li>
  </ul>
</div>

app/views/subjects/show.js.erb
$("#work").html("<%= escape_javascript(render("show_work_list")) %>");