config/routes.rb
Rails.application.routes.draw do
  resources :subject_has_classifications
  resources :subject_heading_types do
    resources :subjects
  end
  resources :subject_heading_type_has_subjects
  resources :classifications do
    resources :subject_has_classifications
  end
  resources :classification_types do
    resources :classifications
  end
  resources :subject_types

  resources :work_has_subjects

  resources :subjects do
    resources :works, :controller => 'manifestations'
    resources :subject_heading_types
    resources :subject_has_classifications
    resources :work_has_subjects
    resources :classifications
  end

  resources :works, :controller => 'manifestations', :except => [:index, :new, :create] do
    resources :subjects
    resources :work_has_subjects
  end

  resources :manifestations do
    resources :work_has_subjects
    resources :subjects
  end
end

app/models/classification.rb
#!/usr/bin/env ruby
# -*- encoding: utf-8 -*-
class Classification < ActiveRecord::Base
  attr_accessible :parent_id, :category, :note, :classification_type_id
  has_many :subject_has_classifications, :dependent => :destroy
  has_many :subjects, :through => :subject_has_classifications
  belongs_to :classification_type, :validate => true
  #has_many_polymorphs :subjects, :from => [:concepts, :places], :through => :subject_has_classifications

  validates_associated :classification_type
  validates_presence_of :category, :classification_type
  validates_uniqueness_of :category, :scope => :classification_type_id
  searchable do
    text :category, :note, :subject
    integer :subject_ids, :multiple => true
    integer :classification_type_id
  end
  #acts_as_nested_set
  #acts_as_taggable_on :tags
  normalize_attributes :category

  paginates_per 10

  private
  def subject
    subjects.collect{|s| [s.term, s.term_transcription]}
  end
end

# == Schema Information
#
# Table name: classifications
#
#  id                     :integer          not null, primary key
#  parent_id              :integer
#  category               :string(255)      not null
#  note                   :text
#  classification_type_id :integer          not null
#  created_at             :datetime
#  updated_at             :datetime
#  lft                    :integer
#  rgt                    :integer
#

app/models/classification_type.rb
class ClassificationType < ActiveRecord::Base
  attr_accessible :name, :display_name, :note
  include MasterModel
  default_scope :order => 'position'
  has_many :classifications
end

# == Schema Information
#
# Table name: classification_types
#
#  id           :integer          not null, primary key
#  name         :string(255)      not null
#  display_name :text
#  note         :text
#  position     :integer
#  created_at   :datetime
#  updated_at   :datetime
#

app/controllers/classifications_controller.rb
# -*- encoding: utf-8 -*-
class ClassificationsController < ApplicationController
  load_and_authorize_resource
  before_filter :get_subject, :get_classification_type
  after_filter :solr_commit, :only => [:create, :update, :destroy]
  #cache_sweeper :subject_sweeper, :only => [:create, :update, :destroy]

  # GET /classifications
  # GET /classifications.json
  def index
    search = Sunspot.new_search(Classification)
    query = params[:query].to_s.strip
    unless query.blank?
      @query = query.dup
      search.build do
        fulltext query
      end
    end
    unless params[:mode] == 'add'
      subject = @subject
      classification_type = @classification_type
      search.build do
        with(:subject_ids).equal_to subject.id if subject
        with(:classification_type_id).equal_to classification_type.id if classification_type
      end
    end

    page = params[:page] || 1
    search.query.paginate(page.to_i, Classification.default_per_page)
    @classifications = search.execute!.results

    session[:params] = {} unless session[:params]
    session[:params][:classification] = params

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @classifications }
    end
  end

  # GET /classifications/1
  # GET /classifications/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @classification }
    end
  end

  # GET /classifications/new
  # GET /classifications/new.json
  def new
    @classification_types = ClassificationType.all
    @classification = Classification.new
    @classification.classification_type = @classification_type

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @classification }
    end
  end

  # GET /classifications/1/edit
  def edit
    @classification_types = ClassificationType.all
  end

  # POST /classifications
  # POST /classifications.json
  def create
    @classification = Classification.new(params[:classification])

    respond_to do |format|
      if @classification.save
        format.html { redirect_to @classification, :notice => t('controller.successfully_created', :model => t('activerecord.models.classification')) }
        format.json { render :json => @classification, :status => :created, :location => @classification }
      else
        @classification_types = ClassificationType.all
        format.html { render :action => "new" }
        format.json { render :json => @classification.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /classifications/1
  # PUT /classifications/1.json
  def update
    respond_to do |format|
      if @classification.update_attributes(params[:classification])
        format.html { redirect_to @classification, :notice => t('controller.successfully_updated', :model => t('activerecord.models.classification')) }
        format.json { head :no_content }
      else
        @classification_types = ClassificationType.all
        format.html { render :action => "edit" }
        format.json { render :json => @classification.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /classifications/1
  # DELETE /classifications/1.json
  def destroy
    @classification = Classification.find(params[:id])
    @classification.destroy

    respond_to do |format|
      format.html { redirect_to classifications_url }
      format.json { head :no_content }
    end
  end

  def get_classification_type
    @classification_type = ClassificationType.find(params[:classification_type_id]) rescue nil
  end
end

app/views/classifications/_form.html.erb
<%= form_for(@classification) do |f| -%>
  <%= f.error_messages -%>

  <div class="field">
    <%= f.label :category -%><br />
    <%= f.text_field :category -%>
  </div>

  <div class="field">
    <%= f.label :note -%><br />
    <%= f.text_area :note, :class => 'resource_textarea' -%>
  </div>

  <div class="field">
    <%= f.label t('activerecord.models.classification_type') -%><br />
    <%= f.select(:classification_type_id, @classification_types.collect{|c| [c.name, c.id]}) -%>
  </div>

  <div class="actions">
    <%= f.submit -%>
  </div>
<%- end -%>

app/views/classifications/_index.html.erb
<div id="content_detail" class="ui-corner-all">
<h1 class="title"><%= t('page.listing', :model => t('activerecord.models.classification')) -%></h1>
<div id="content_list">

<div class="search_form">
  <%= form_for :classifications, :url => classifications_path, :html => {:method => 'get'} do -%>
    <p>
      <%= t('page.search_term') -%>: <%= search_field_tag 'query', h(@query), {:id => 'search_form_top', :class => 'search_form', :placeholder => t('page.search_term')} -%>
      <%= submit_tag t('page.search') -%>
    </p>
  <%- end -%>
</div>

<table class="table table-striped index">
  <tr>
    <th><%= t('activerecord.attributes.classification.category') -%></th>
    <th><%= t('activerecord.attributes.classification.note') -%></th>
    <th><%= t('activerecord.models.classification_type') -%></th>
    <th></th>
  </tr>

<%- @classifications.each do |classification| -%>
  <tr class="line<%= cycle("0", "1") -%>">
    <td><%= link_to classification.category, classification -%></td>
    <td><%= classification.note -%></td>
    <td><%= link_to classification.classification_type.display_name.localize, classification.classification_type -%></td>
    <td>
      <%- if can? :destroy, classification -%>
        <%= link_to t('page.edit'), edit_classification_path(classification) -%>
        <%= link_to t('page.destroy'), classification, :data => {:confirm => t('page.are_you_sure')}, :method => :delete -%>
      <%- end -%>
    </td>
  </tr>
<%- end -%>
</table>

<%= paginate(@classifications) -%>

</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <%- if can? :create, Classification -%>
      <%- if @classification_type -%>
        <li><%= link_to t('page.new', :model => t('activerecord.models.classification')), new_classification_type_classification_path(@classification_type) -%></li>
      <%- else -%>
        <li><%= link_to t('page.new', :model => t('activerecord.models.classification')), new_classification_path -%></li>
      <%- end -%>
    <%- end -%>
  </ul>
</div>

app/views/classifications/_index_subject.html.erb
<div id="content_detail" class="ui-corner-all">
<h1 class="title"><%= t('page.listing', :model => t('activerecord.models.classification')) -%></h1>
<div id="content_list">

<h2><%= link_to @subject.term, @subject -%></h2>

<div class="search_form">
  <%= form_for :classifications, :url => subject_classifications_path(@subject), :html => {:method => 'get'} do -%>
    <p>
      <%= t('page.search_term') -%>: <%= search_field_tag 'query', h(@query), {:id => 'search_form_top', :class => 'search_form', :placeholder => t('page.search_term')} -%>
      <%= submit_tag t('page.search') -%>
      <%- if can? :create, SubjectHasClassification -%>
        <%= render 'page/add' %>
      <%- end -%>
    </p>
  <%- end -%>
</div>

<table class="table table-striped index">
  <tr>
    <th><%= t('activerecord.models.classification') -%></th>
    <th><%= t('activerecord.attributes.classification.note') -%></th>
    <th><%= t('activerecord.models.classification_type') -%></th>
    <th></th>
    <th></th>
  </tr>

<%- @classifications.each do |classification| -%>
  <tr class="line<%= cycle("0", "1") -%>">
    <td><%= link_to classification.category, subject_classification_path(@subject, classification) -%></td>
    <td><%= classification.note -%></td>
    <td><%= classification.classification_type.display_name.localize -%></td>
    <td>
      <%- if can? :destroy, classification -%>
        <%= link_to t('page.edit'), edit_classification_path(classification) -%>
      <% end %>
    </td>
    <td>
      <%- if can? :destroy, classification -%>
        <%- if params[:mode] == 'add' -%>
          <%= link_to t('page.add'), new_subject_subject_has_classification_path(@subject, :classification_id => classification.id) unless @subject.classifications.include?(classification) -%>
        <%- else -%>
          <%- has_classification = @subject.subject_has_classifications.find_by_classification_id(classification) -%>
          <%= link_to t('page.destroy'), subject_subject_has_classification_path(@subject, has_classification), :data => {:confirm => t('page.are_you_sure')}, :method => :delete if has_classification -%>
        <%- end -%>
      <%- end -%>
    </td>
  </tr>
<%- end -%>
</table>

<%= paginate(@classifications) -%>
</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <%- if can? :create, Classification -%>
      <li><%= link_to t('page.new', :model => t('activerecord.models.classification')), new_classification_path -%></li>
    <%- end -%>
  </ul>
</div>

app/views/classifications/edit.html.erb
<div id="content_detail" class="ui-corner-all">
<h1 class="title"><%= t('page.editing', :model => t('activerecord.models.classification')) -%></h1>
<div id="content_list">
  <%= render 'form' %>
</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <li><%= link_to t('page.show'), @classification -%></li>
    <li><%= link_to t('page.back'), classifications_path -%></li>
  </ul>
</div>

app/views/classifications/index.html.erb
<%- if @subject -%>
  <%= render 'index_subject' -%>
<%- else -%>
  <%= render 'index' -%>
<%- end -%>

app/views/classifications/new.html.erb
<div id="content_detail" class="ui-corner-all">
<h1 class="title"><%=  t('page.new', :model => t('activerecord.models.classification')) -%></h1>
<div id="content_list">
  <%= render 'form' %>
</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <li><%= link_to t('page.back'), :back -%></li>
  </ul>
</div>

app/views/classifications/show.html.erb
<div id="content_detail" class="ui-corner-all">
<h1 class="title"><%= t('page.showing', :model => t('activerecord.models.classification')) -%></h1>
<div id="content_list">
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('activerecord.attributes.classification.category') -%>:</strong>
  <%= @classification.category %>
</p>

<p>
  <strong><%= t('activerecord.attributes.classification.note') -%>:</strong>
  <%= @classification.note %>
</p>

<p>
  <strong><%= t('activerecord.models.classification_type') -%>:</strong>
  <%= link_to @classification.classification_type.display_name.localize, @classification.classification_type %>
</p>

</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <li><%= link_to t('page.edit'), edit_classification_path(@classification) %></li>
    <li><%= back_to_index(flash[:page_info]) -%></li>
  </ul>
</div>