config/routes.rb
Rails.application.routes.draw do
  resources :subject_has_classifications
  resources :subject_heading_types do
    resources :subjects
  end
  resources :subject_heading_type_has_subjects
  resources :classifications do
    resources :subject_has_classifications
  end
  resources :classification_types do
    resources :classifications
  end
  resources :subject_types

  resources :work_has_subjects

  resources :subjects do
    resources :works, :controller => 'manifestations'
    resources :subject_heading_types
    resources :subject_has_classifications
    resources :work_has_subjects
    resources :classifications
  end

  resources :works, :controller => 'manifestations', :except => [:index, :new, :create] do
    resources :subjects
    resources :work_has_subjects
  end

  resources :manifestations do
    resources :work_has_subjects
    resources :subjects
  end
end

app/models/work_has_subject.rb
class WorkHasSubject < ActiveRecord::Base
  attr_accessible :subject_id, :work_id, :position
  belongs_to :subject
  belongs_to :work, :class_name => 'Manifestation'

  validates_presence_of :work, :subject #, :subject_type
  validates_associated :work, :subject
  validates_uniqueness_of :subject_id, :scope => :work_id
  after_save :reindex
  after_destroy :reindex

  acts_as_list :scope => :work_id

  def reindex
    work.try(:index)
    subject.try(:index)
  end
end

# == Schema Information
#
# Table name: work_has_subjects
#
#  id           :integer          not null, primary key
#  subject_id   :integer
#  subject_type :string(255)
#  work_id      :integer
#  position     :integer
#  created_at   :datetime
#  updated_at   :datetime
#

app/controllers/work_has_subjects_controller.rb
class WorkHasSubjectsController < ApplicationController
  load_and_authorize_resource
  helper_method :get_work, :get_subject
  after_filter :solr_commit, :only => [:create, :update, :destroy]
  #cache_sweeper :subject_sweeper, :only => [:create, :update, :destroy]

  # GET /work_has_subjects
  # GET /work_has_subjects.json
  def index
    get_work; get_subject
    if @work
      @work_has_subjects = @work.work_has_subjects.page(params[:page])
    elsif @subject
      @work_has_subjects = @subject.work_has_subjects.page(params[:page])
    else
      @work_has_subjects = WorkHasSubject.page(params[:page])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @work_has_subjects }
    end
  end

  # GET /work_has_subjects/1
  # GET /work_has_subjects/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @work_has_subject }
    end
  end

  # GET /work_has_subjects/new
  # GET /work_has_subjects/new.json
  def new
    get_work; get_subject
    @work_has_subject = WorkHasSubject.new(:work => @work, :subject => @subject)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @work_has_subject }
    end
  end

  # GET /work_has_subjects/1/edit
  def edit
  end

  # POST /work_has_subjects
  # POST /work_has_subjects.json
  def create
    @work_has_subject = WorkHasSubject.new(params[:work_has_subject])

    respond_to do |format|
      if @work_has_subject.save
        format.html { redirect_to @work_has_subject, :notice => t('controller.successfully_created', :model => t('activerecord.models.work_has_subject')) }
        format.json { render :json => @work_has_subject, :status => :created, :location => @work_has_subject }
      else
        format.html { render :action => "new" }
        format.json { render :json => @work_has_subject.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /work_has_subjects/1
  # PUT /work_has_subjects/1.json
  def update
    get_work
    if @work and params[:move]
      move_position(@work_has_subject, params[:move], false)
      redirect_to work_work_has_subjects_url(@work)
      return
    end

    respond_to do |format|
      if @work_has_subject.update_attributes(params[:work_has_subject])
        format.html { redirect_to @work_has_subject, :notice => t('controller.successfully_updated', :model => t('activerecord.models.work_has_subject')) }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @work_has_subject.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /work_has_subjects/1
  # DELETE /work_has_subjects/1.json
  def destroy
    get_work; get_subject
    @work_has_subject.destroy

    respond_to do |format|
      format.html {
        case
        when @work
          redirect_to work_work_has_subjects_url(@work)
        when @subject
          redirect_to subject_work_has_subjects_url(@subject)
        else
          redirect_to work_has_subjects_url
        end
      }
      format.json { head :no_content }
    end
  end
end

app/views/work_has_subjects/_form.html.erb
<%= form_for(@work_has_subject) do |f| %>
  <% if @work_has_subject.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@work_has_subject.errors.count, "error") %> prohibited this work_has_subject from being saved:</h2>
    <ul>
    <% @work_has_subject.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :work_id %><br />
    <%= f.text_field :work_id %>
  </div>
  <div class="field">
    <%= f.label :subject_id %><br />
    <%= f.text_field :subject_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/work_has_subjects/edit.html.erb
<div id="content_detail" class="ui-corner-all">
<h1 class="title"><%= t('page.editing', :model => t('activerecord.models.work_has_subject')) -%></h1>
<div id="content_list">

<%= form_for(@work_has_subject) do |f| -%>
  <%= f.error_messages -%>

  <div class="field">
    <%= f.label :work -%><br />
    <%= f.text_field :work_id -%>
  </div>
  <div class="field">
    <%= f.label :subject -%><br />
    <%= f.text_field :subject_id -%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<%- end -%>

</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <li><%= link_to t('page.show'), @work_has_subject -%></li>
    <li><%= link_to t('page.back'), work_has_subjects_path -%></li>
  </ul>
</div>

app/views/work_has_subjects/index.html.erb
<div id="content_detail" class="ui-corner-all">
<h1 class="title"><%= t('page.listing', :model => t('activerecord.models.work_has_subject')) -%></h1>
<div id="content_list">

<table class="table table-striped index">
  <tr>
    <th><%= t('activerecord.models.subject') -%></th>
    <th><%= t('activerecord.attributes.work_has_subject.work') -%></th>
  </tr>

<%- @work_has_subjects.each do |work_has_subject| -%>
  <tr class="line<%= cycle("0", "1") -%>">
    <td><%= link_to work_has_subject.subject.term, work_has_subject.subject -%></td>
    <!-- TODO: Manifestation以外 -->
    <td><%= link_to work_has_subject.work.original_title, work_has_subject.work -%></td>
    <td><%= link_to t('page.show'), work_has_subject -%></td>
    <td><%= link_to t('page.edit'), edit_work_has_subject_path(work_has_subject) -%></td>
    <td><%= link_to t('page.destroy'), work_has_subject, :data => {:confirm => t('page.are_you_sure')}, :method => :delete -%></td>
  </tr>
<%- end -%>
</table>

<%= paginate(@work_has_subjects) -%>
</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <li><%= link_to t('page.new', :model => t('activerecord.models.work_has_subject')), new_work_has_subject_path -%></li>
  </ul>
</div>

app/views/work_has_subjects/new.html.erb
<div id="content_detail" class="ui-corner-all">
<h1 class="title"><%= t('page.new', :model => t('activerecord.models.work_has_subject')) -%></h1>
<div id="content_list">

<%= form_for(@work_has_subject) do |f| -%>
  <%= f.error_messages -%>

  <div class="field">
    <%= f.label :work -%><br />
    <%- if @work_has_subject.work -%>
      <%= link_to @work_has_subject.work.original_title, @work_has_subject.work -%>
      <%= f.hidden_field :work_id -%>
    <%- else -%>
      <%= f.text_field :work_id -%>
    <%- end -%>
  </div>
  <div class="field">
    <%= f.label :subject -%><br />
    <%- if @work_has_subject.subject -%>
      <%= link_to @work_has_subject.subject.term, @work_has_subject.subject -%>
      <%= f.hidden_field :subject_id -%>
    <%- else -%>
      <%= f.text_field :subject_id -%>
    <%- end -%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<%- end -%>

</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <%- if @work -%>
      <li><%= link_to t('page.listing', :model => t('activerecord.models.work')), work_subjects_path(@work) -%></li>
    <%- else -%>
      <li><%= back_to_index -%></li>
    <%- end -%>
  </ul>
</div>

app/views/work_has_subjects/show.html.erb
<div id="content_detail" class="ui-corner-all">
<h1 class="title"><%= t('page.showing', :model => t('activerecord.models.work_has_subject')) -%></h1>
<div id="content_list">
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('activerecord.attributes.work_has_subject.work') -%>:</strong>
  <!-- TODO: Manifestation以外 -->
  <%= link_to @work_has_subject.work.original_title, @work_has_subject.work if @work_has_subject.work -%>
</p>

<p>
  <strong><%= t('activerecord.attributes.work_has_subject.subject') -%>:</strong>
  <%= link_to @work_has_subject.subject.term, @work_has_subject.subject -%>
</p>

</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <li><%= link_to t('page.listing', :model => t('activerecord.models.work_has_subject')), work_has_subjects_path -%></li>
    <li><%= link_to t('page.listing', :model => t('activerecord.models.subject')), subjects_path -%></li>
  </ul>
</div>