config/routes.rb
Rails.application.routes.draw do
  resources :subject_has_classifications
  resources :subject_heading_types do
    resources :subjects
  end
  resources :subject_heading_type_has_subjects
  resources :classifications do
    resources :subject_has_classifications
  end
  resources :classification_types do
    resources :classifications
  end
  resources :subject_types

  resources :work_has_subjects

  resources :subjects do
    resources :works, :controller => 'manifestations'
    resources :subject_heading_types
    resources :subject_has_classifications
    resources :work_has_subjects
    resources :classifications
  end

  resources :works, :controller => 'manifestations', :except => [:index, :new, :create] do
    resources :subjects
    resources :work_has_subjects
  end

  resources :manifestations do
    resources :work_has_subjects
    resources :subjects
  end
end

app/controllers/classification_types_controller.rb
class ClassificationTypesController < InheritedResources::Base
  respond_to :html, :json
  load_and_authorize_resource

  def update
    @classification_type = ClassificationType.find(params[:id])
    if params[:move]
      move_position(@classification_type, params[:move])
      return
    end
    update!
  end
end

app/views/classification_types/_form.html.erb
<%= form_for(@classification_type) do |f| %>
  <%= f.error_messages %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :class => 'short_name' %>
  </div>
  <div class="field">
    <%= f.label :display_name %><br />
    <%= f.text_area :display_name, :class => 'resource_textarea' %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note, :class => 'resource_textarea' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/classification_types/edit.html.erb
<div id="content_detail" class="ui-corner-all">
<h1 class="title"><%= t('page.editing', :model => t('activerecord.models.classification_type')) -%></h1>
<div id="content_list">
  <%= render 'form' %>
</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <li><%= link_to t('page.show'), @classification_type -%></li>
    <li><%= link_to t('page.back'), classification_types_path -%></li>
  </ul>
</div>

app/views/classification_types/index.html.erb
<div id="content_detail" class="ui-corner-all">
<h1 class="title"><%= t('page.listing', :model => t('activerecord.models.classification_type')) -%></h1>
<div id="content_list">

<table class="table table-striped index">
  <tr>
    <th id="position"></th>
    <th><%= t('activerecord.attributes.classification_type.name') -%></th>
    <th><%= t('activerecord.attributes.classification_type.display_name') -%></th>
    <th><%= t('activerecord.attributes.classification_type.note') -%></th>
    <th></th>
  </tr>

<%- @classification_types.each do |classification_type| -%>
  <tr class="line<%= cycle("0", "1") -%>">
    <td>
      <%- if can? :update, classification_type -%>
        <%= move_position(classification_type) -%>
      <%- end -%>
    </td>
    <td><%= link_to classification_type.name, classification_type -%></td>
    <td><%= link_to classification_type.display_name.localize, classification_type -%></td>
    <td><%= classification_type.note -%></td>
    <td>
      <%- if can? :update, classification_type -%>
        <%= link_to t('page.edit'), edit_classification_type_path(classification_type) -%>
      <% end %>
      <%- if can? :destroy, classification_type -%>
        <%= link_to t('page.destroy'), classification_type, :data => {:confirm => t('page.are_you_sure')}, :method => :delete -%>
      <%- end -%>
    </td>
  </tr>
<%- end -%>
</table>

</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <%- if can? :create, ClassificationType -%>
      <li><%= link_to t('page.new', :model => t('activerecord.models.classification_type')), new_classification_type_path -%></li>
    <%- end -%>
  </ul>
</div>

app/views/classification_types/new.html.erb
<div id="content_detail" class="ui-corner-all">
<h1 class="title"><%= t('page.new', :model => t('activerecord.models.classification_type')) -%></h1>
<div id="content_list">
  <%= render 'form' %>
</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <li><%= link_to t('page.back'), classification_types_path -%></li>
  </ul>
</div>

app/views/classification_types/show.html.erb
<div id="content_detail" class="ui-corner-all">
<h1 class="title"><%= t('page.showing', :model => t('activerecord.models.classification_type')) -%></h1>
<div id="content_list">
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('activerecord.attributes.classification_type.name') -%>:</strong>
  <%= @classification_type.name -%>
</p>

<p>
  <strong><%= t('activerecord.attributes.classification_type.display_name') -%>:</strong>
  <%= @classification_type.display_name.localize -%>
</p>

<p>
  <strong><%= t('activerecord.attributes.classification_type.note') -%>:</strong>
  <%= @classification_type.note -%>
</p>

</div>
</div>

<div id="submenu" class="ui-corner-all">
  <ul>
    <li><%= link_to t('page.listing', :model => t('activerecord.models.classification')), classification_type_classifications_path(@classification_type) -%></li>
    <li><%= link_to t('page.edit'), edit_classification_type_path(@classification_type) -%></li>
    <li><%= back_to_index(flash[:page_info]) -%></li>
  </ul>
</div>